/* Per-calculator pages.

   These files are generated by tools/calcpage.js and committed, so the risk
   is the same one tools/prerender.js has: the source moves, the committed
   copy does not, and the site ships a page describing a calculator that no
   longer works that way. The first assertion here is therefore the important
   one — regenerate, and compare byte for byte.

   The rest guard the things that make a page worth having at all: a title
   short enough to survive Google's truncation, a canonical that points at a
   URL the host actually answers, and no third-party request smuggled in by a
   content file. That last one matters most: the footers promise nothing is
   sent anywhere, and prose is the easiest place to break it by pasting an
   image or an embed.

   Skips itself when content/pages.json is absent, so the suite stays green on
   a checkout that has no such pages yet. */

'use strict';

var fs = require('fs');
var path = require('path');
var H = require('./harness');

var TITLE = 'Per-calculator pages';
var ROOT = path.join(__dirname, '..');

function run(page) {
  var manifestPath = path.join(ROOT, 'content', 'pages.json');
  if (!fs.existsSync(manifestPath)) {
    H.suite('per-calculator pages');
    H.check('skipped — no content/pages.json yet', true);
    return;
  }

  var calcpage = require('../tools/calcpage.js');
  var specs = calcpage.manifest();
  var indexHtml = page.html;
  var data = page.sandbox.PM_DATA;

  var ids = {};
  H.eachCard(data, function (card) { ids[card.id] = card.name; });

  H.suite('page freshness');
  H.check('the manifest lists at least one page', specs.length > 0);

  var slugs = {};
  specs.forEach(function (spec) {
    var file = spec.slug + '.html';
    var full = path.join(ROOT, file);

    H.check(file + ': its calculator exists in PM_DATA', !!ids[spec.card],
      'no card with id ' + spec.card);
    H.check(file + ': its content file exists',
      fs.existsSync(path.join(ROOT, 'content', spec.slug + '.html')));
    H.check(file + ': the slug is unique', !slugs[spec.slug]);
    slugs[spec.slug] = true;

    if (!fs.existsSync(full)) {
      H.check(file + ': is committed', false, 'run node tools/calcpage.js --all');
      return;
    }

    var onDisk = fs.readFileSync(full, 'utf8');
    var rebuilt;
    try {
      rebuilt = calcpage.build(spec, indexHtml);
    } catch (e) {
      H.check(file + ': regenerates without error', false, e.message);
      return;
    }

    /* The one that catches real drift: index.html changed, the page did not. */
    H.check(file + ': is current with index.html', onDisk === rebuilt,
      'stale by ' + Math.abs(onDisk.length - rebuilt.length) +
      ' bytes — run node tools/calcpage.js --all');

    H.suite('page metadata');
    var title = (/<title>([\s\S]*?)<\/title>/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the title survives Google truncation',
      title.length > 0 && title.length <= 62, title.length + ' characters');

    var desc = (/<meta name="description" content="([^"]*)"/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the description is a usable length',
      desc.length >= 110 && desc.length <= 175, desc.length + ' characters');

    var canonical = (/rel="canonical" href="([^"]*)"/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the canonical points at this very file',
      canonical === 'https://yazeed.blog/' + file, canonical);

    H.check(file + ': there is exactly one h1',
      (onDisk.match(/<h1[\s>]/g) || []).length === 1);

    H.check(file + ': it carries structured data',
      /"@type": "SoftwareApplication"/.test(onDisk) &&
      /"@type": "BreadcrumbList"/.test(onDisk));

    /* Same promise the desk makes. A pasted image or embed in a content file
       is the easy way to break it without noticing.

       What counts is a request the page makes on its own — a src, or a href
       on <link>. An <a href> to another site is a link the reader may choose
       to follow, not a request, and the citations in PM_DATA are exactly
       that. Script bodies are excluded too: the URLs in there are strings in
       the calculator data, not markup. */
    H.suite('no third-party requests');
    var markup = onDisk.replace(/<script[\s\S]*?<\/script>/gi, '');
    var external = [];
    var re = /<link\b[^>]*\bhref\s*=\s*"(https?:\/\/[^"]+)"|\bsrc\s*=\s*"(https?:\/\/[^"]+)"/gi;
    var m;
    while ((m = re.exec(markup)) !== null) {
      var url = m[1] || m[2];
      if (url.indexOf('https://yazeed.blog/') !== 0) external.push(url);
    }
    H.deep(file + ': requests nothing from another origin', external.slice(0, 3), []);

    /* A page nothing links to and the sitemap does not list is a page Google
       has no route to. Shipping one is the quiet way to do all this work and
       get none of it. */
    H.suite('discoverability');
    var sitemap = fs.existsSync(path.join(ROOT, 'sitemap.xml'))
      ? fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8') : '';
    H.check(file + ': is listed in sitemap.xml',
      sitemap.indexOf('<loc>https://yazeed.blog/' + file + '</loc>') !== -1);
    H.check(file + ': links back to the desk',
      onDisk.indexOf('href="/"') !== -1);
  });
}

module.exports = { title: TITLE, run: run };

if (require.main === module) {
  H.reset();
  run(H.loadPage('index.html'));
  H.report(TITLE);
}
