/* Per-calculator pages.

   These files are generated by tools/calcpage.js and committed, so the risk
   is the same one tools/prerender.js has: the source moves, the committed
   copy does not, and the site ships a page describing a calculator that no
   longer works that way. The first assertion here is therefore the important
   one — regenerate, and compare byte for byte.

   The rest guard the things that make a page worth having at all, and the
   things the SEO plan requires of this phase: a title short enough to survive
   Google's truncation, a canonical that points at a URL the host actually
   answers, no third-party request other than the named Google Analytics tag,
   real long-form prose (not a thin keyword page), a breadcrumb that Google
   can parse, a footer that carries the live calculator count, and a static
   link from the desk to every page so a crawler has a route to it. */

'use strict';

var fs = require('fs');
var path = require('path');
var H = require('./harness');

var TITLE = 'Per-calculator pages';
var ROOT = path.join(__dirname, '..');

/* The minimum body prose. The plan calls for long-form cluster pages, not
   thin keyword pages; a content file under this length is the shape Google
   filters as built-for-rankings rather than for readers. Counted as plain
   text — tags and script bodies stripped — so a page that pads with markup
   does not pass. */
var MIN_WORDS = 1000;

/* The card ids a generated page's definitions actually contain. Read from
   the shipped text rather than by evaluating it: a page that went back to
   embedding the whole desk and filtering at run time would evaluate to one
   card and still have sent all thirty-four. */
function shippedCardIds(html) {
  var re = /<script>([\s\S]*?)<\/script>/g, m;
  while ((m = re.exec(html)) !== null) {
    if (m[1].indexOf('var PM_DATA = (function') === -1) continue;
    var ids = m[1].match(/^          id: '([^']+)',$/gm) || [];
    return ids.map(function (line) { return /'([^']+)'/.exec(line)[1]; });
  }
  return [];
}

function stripMarkup(html) {
  return String(html)
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function wordCount(text) {
  if (!text) return 0;
  return text.split(/\s+/).filter(Boolean).length;
}

function sameText(a, b) {
  return String(a).replace(/\r\n/g, '\n') === String(b).replace(/\r\n/g, '\n');
}

/* The same phrase test tests/counts.js uses, so the footer on a subpage
   agrees with the desk's count down to the same regex. */
function hasCount(text, count, noun) {
  var prefix = noun === 'calculators' ? '(?:(?:PM|project-management)\\s+)?' : '';
  return new RegExp('\\b' + count + '\\s+' + prefix + noun + '\\b', 'i').test(text);
}

var GA_SRC = 'https://www.googletagmanager.com/gtag/js?id=G-J4XTN125MF';

function gaHits(html) {
  return (html.match(/gtag\/js\?id=G-J4XTN125MF/g) || []).length;
}

function allowedRequest(url) {
  return url.indexOf('https://yazeed.blog/') === 0 || url === GA_SRC;
}

/* Keep external <script src> (the Google tag) visible, but drop inline
   script bodies so a URL inside calculator data is not treated as a request. */
function strayRequests(html) {
  var markup = String(html).replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi,
    function (all, attrs) {
      if (/\bsrc\s*=/.test(attrs)) return all;
      return '<script' + attrs + '></script>';
    });
  var found = [];
  var re = /<(?:link|script|img)\b[^>]*\b(?:href|src)\s*=\s*"(https?:\/\/[^"]+)"/gi;
  var m;
  while ((m = re.exec(markup)) !== null) {
    if (!allowedRequest(m[1])) found.push(m[1]);
  }
  return found;
}

function run(page) {
  var manifestPath = path.join(ROOT, 'content', 'pages.json');
  /* pages.json is part of the shipped surface for this phase; the suite
     fails if it is missing rather than skipping, so a checkout that has
     lost it is caught here instead of silently shipping no pages. */
  H.suite('manifest');
  H.check('content/pages.json exists', fs.existsSync(manifestPath),
    'run the phase-one work; this suite no longer skips');

  if (!fs.existsSync(manifestPath)) return;

  var calcpage = require('../tools/calcpage.js');
  var specs = calcpage.manifest();
  var indexHtml = page.html;
  var data = page.sandbox.PM_DATA;
  var totalCards = 0;

  var ids = {};
  H.eachCard(data, function (card) {
    ids[card.id] = card.name;
    totalCards += 1;
  });

  H.suite('page freshness');
  H.check('the manifest lists at least one page', specs.length > 0);

  var slugs = {};
  specs.forEach(function (spec) {
    var file = spec.slug + '.html';
    var full = path.join(ROOT, file);

    H.check(file + ': its calculator exists in PM_DATA', !!ids[spec.card],
      'no card with id ' + spec.card);
    H.check(file + ': its content file exists',
      fs.existsSync(path.join(ROOT, 'content', spec.slug + '.html')));
    H.check(file + ': the slug is unique', !slugs[spec.slug]);
    slugs[spec.slug] = true;

    if (!fs.existsSync(full)) {
      H.check(file + ': is committed', false, 'run node tools/calcpage.js --all');
      return;
    }

    var onDisk = fs.readFileSync(full, 'utf8');
    var rebuilt;
    try {
      rebuilt = calcpage.build(spec, indexHtml);
    } catch (e) {
      H.check(file + ': regenerates without error', false, e.message);
      return;
    }

    /* The one that catches real drift: index.html changed, the page did not. */
    H.check(file + ': is current with index.html', sameText(onDisk, rebuilt),
      'stale by ' + Math.abs(onDisk.length - rebuilt.length) +
      ' bytes — run node tools/calcpage.js --all');

    H.suite('page metadata');
    var title = (/<title>([\s\S]*?)<\/title>/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the title survives Google truncation',
      title.length > 0 && title.length <= 62, title.length + ' characters');

    var desc = (/<meta name="description" content="([^"]*)"/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the description is a usable length',
      desc.length >= 110 && desc.length <= 175, desc.length + ' characters');

    var canonical = (/rel="canonical" href="([^"]*)"/.exec(onDisk) || [])[1] || '';
    H.check(file + ': the canonical points at this very file',
      canonical === 'https://yazeed.blog/' + file, canonical);

    H.check(file + ': there is exactly one h1',
      (onDisk.match(/<h1[\s>]/g) || []).length === 1);

    H.check(file + ': it carries structured data',
      /"@type": "SoftwareApplication"/.test(onDisk) &&
      /"@type": "BreadcrumbList"/.test(onDisk));

    H.suite('third-party requests');
    H.check(file + ': carries the Google tag once', gaHits(onDisk) === 1);
    H.deep(file + ': requests no other origin', strayRequests(onDisk).slice(0, 3), []);

    H.suite('long-form prose');
    var prosePath = path.join(ROOT, 'content', spec.slug + '.html');
    var prose = fs.existsSync(prosePath) ? fs.readFileSync(prosePath, 'utf8') : '';
    var words = wordCount(stripMarkup(prose));
    H.check(file + ': content prose reaches the long-form minimum',
      words >= MIN_WORDS, words + ' words (need ' + MIN_WORDS + ')');

    H.suite('breadcrumb');
    /* Google requires `item` on every ListItem except the last. A middle
       entry with only `name` is the easy mistake to make when the trail is
       three levels; this catches it for any depth. */
    var jsonMatch = /<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/i.exec(onDisk);
    var jsonLd = null;
    if (jsonMatch) {
      try { jsonLd = JSON.parse(jsonMatch[1]); } catch (e) { jsonLd = null; }
    }
    var crumbs = null;
    if (jsonLd && jsonLd['@graph']) {
      jsonLd['@graph'].forEach(function (node) {
        if (node['@type'] === 'BreadcrumbList') crumbs = node.itemListElement;
      });
    } else if (jsonLd && jsonLd.itemListElement) {
      crumbs = jsonLd.itemListElement;
    }
    H.check(file + ': has a BreadcrumbList', !!crumbs);
    if (crumbs) {
      var missing = [];
      crumbs.forEach(function (item, i) {
        if (i < crumbs.length - 1 && !item.item) missing.push('position ' + item.position);
      });
      H.check(file + ': every non-final breadcrumb ListItem has an item',
        missing.length === 0, 'missing item on ' + missing.join(', '));
    }

    H.suite('footer count');
    H.check(file + ': the footer states the live calculator count',
      hasCount(onDisk, totalCards, 'calculators'),
      'expected ' + totalCards + ' calculators in the footer');

    /* A page about one calculator should carry one calculator. It used to
       carry all thirty-four and filter the rest away in the browser, which
       cost every visitor about 134 kB of definitions the page then discarded
       — invisible on screen, so nothing but a check like this would notice
       it coming back. Counted from the definitions the page actually ships,
       not from the rendered DOM, because the point is the bytes. */
    H.suite('ships one calculator, not the whole desk');
    var shipped = shippedCardIds(onDisk);
    H.deep(file + ': the definitions hold only its own card',
      shipped, [spec.card]);
    H.check(file + ': no other calculator\'s prose rides along',
      shipped.length === 1,
      'found ' + shipped.length + ' cards: ' + shipped.slice(0, 5).join(', '));

    H.suite('discoverability');
    var sitemap = fs.existsSync(path.join(ROOT, 'sitemap.xml'))
      ? fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8') : '';
    H.check(file + ': is listed in sitemap.xml',
      sitemap.indexOf('<loc>https://yazeed.blog/' + file + '</loc>') !== -1);
    H.check(file + ': links back to the desk',
      onDisk.indexOf('href="/"') !== -1);
  });

  /* A page nothing on the desk links to is a page Google has no route to.
     The link must be in the static markup — the prerendered mirror inside
     #calc-sections — not only a string the runtime builds, because a fetcher
     that runs no JavaScript never sees the runtime's DOM. */
  H.suite('desk links to every page');
  var indexOnDisk = fs.existsSync(path.join(ROOT, 'index.html'))
    ? fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8') : '';
  specs.forEach(function (spec) {
    var file = spec.slug + '.html';
    H.check('index.html links to ' + file,
      indexOnDisk.indexOf('href="' + file + '"') !== -1,
      'no static href="' + file + '" in index.html — run node tools/prerender.js');
  });

  /* The sitemap is generated from the same `updated` field the byline and
     the JSON-LD dates come from, so a page cannot tell a reader one date and
     a crawler another. Regenerate and compare, exactly as the pages above
     are compared — a hand-edit here is the drift this replaced. */
  H.suite('sitemap is generated, not typed');
  var sitemapTool = require('../tools/sitemap.js');
  var sitemapPath = path.join(ROOT, sitemapTool.FILE);
  H.eq(sitemapTool.FILE + ': matches the manifest',
    fs.existsSync(sitemapPath) ? fs.readFileSync(sitemapPath, 'utf8') : '',
    sitemapTool.build(),
    'stale — run `node tools/sitemap.js`');
  specs.forEach(function (spec) {
    H.check(sitemapTool.FILE + ': ' + spec.slug + ' carries its own `updated`',
      sitemapTool.build().indexOf('<lastmod>' + spec.updated + '</lastmod>') !== -1,
      'expected lastmod ' + spec.updated);
  });

  H.suite('Google tag on every shipped page');
  ['index.html', '404.html', 'pm-calculation-desk.html', 'wbs-estimation-toolkit.html']
    .forEach(function (file) {
      var html = fs.readFileSync(path.join(ROOT, file), 'utf8');
      H.check(file + ': carries the Google tag once', gaHits(html) === 1);
      H.deep(file + ': requests no other origin', strayRequests(html).slice(0, 3), []);
    });
}

module.exports = { title: TITLE, run: run };

if (require.main === module) {
  H.reset();
  run(H.loadPage('index.html'));
  H.report(TITLE);
}
